name: "Build"

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    if: (github.event_name == 'pull_request' || github.event_name == 'push') && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build 
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore -o finalbuild-${{ matrix.os }}

    - name: Test
      run: dotnet test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: foggycam-${{ matrix.os }}.zip
        path: finalbuild-${{ matrix.os }}
    
    # - name: Download artifact
    #   uses: actions/download-artifact@v2
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     name: foggycam-${{ matrix.os }}.zip
    #     path: /

    - name: ZIP Release
      if: startsWith(github.ref, 'refs/tags/')
      run: apt-get install zip | zip foggycam-${{ matrix.os }}.zip finalbuild-${{ matrix.os }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: foggycam-${{ matrix.os }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
